### PR TITLE
fix gpuagent config & update doc

### LINKED ISSUE #31: wrong resource file name
I continued to build `gpu-agent` and found that `ts_agent.yaml` in
https://github.com/nebuly-ai/nos/blob/a32426d8d47649e91b874ffecb8df793159d7a5f/config/gpuagent/manager/kustomization.yaml#L2
was missing.
I think it should be `gpu_agent.yaml`?

### LINKED ISSUE #32: doc: wrong make targets
While building the nos I found the doc was a bit outdated.
The make targets in [this](https://docs.nebuly.com/nos/developer/getting-started/#build-components) part should all begin with `docker-`.

### PR DESCRIPTION
**Pull request by WindowsXp-Beta**
fix #31
fix #32
I'm not sure if I fix the formatting errors correctly (I just removed some unnecessary new lines and trailing spaces) so I only modified the `getting-started.md`.
I checked it in mkdocs locally and it looked ok. However, it seems that you've customized the material theme and the `mkdocs.yaml` in the doc folder is not complete so I'm not sure if these new lines and spaces are intentional.
If I'm right, I could modify the rest files.

### CODE REVIEW

**Comment by nebuly-ai** [comment]
Thank you @WindowsXp-Beta for the contribution!

**Comment by Telemaco019** [comment]
Hi @WindowsXp-Beta, I've reviewed the PR and it looks great! The new lines and spaces were unintentional, thanks for cleaning them up! 

I've just left a comment regarding a small typo that causes the rendering error I was referring to. If you could also fix it that would be awesome! The rest looks perfect to me, thanks for the contribution!

Regarding the custom material theme, if you want to try it out you can check out [this repository](https://github.com/nebuly-ai/docs) we use for hosting the [documentation](https://docs.nebuly.com/), which contains the full `mkdocs.yaml` config. The repo includes `nos` as a Git sub-module, so you can clone it as follows: 

```git clone --recurse-submodules https://github.com/nebuly-ai/docs.git```

You can then run `make serve` from the root dir of the repository for starting Mkdocs locally :)

**Comment by WindowsXp-Beta** [comment]
> I've just left a comment

Excuse me, where is the comment?

**Comment by WindowsXp-Beta** [comment]
lol. not a big deal. I've fixed it.
BTW, extra new lines and trailing white spaces exist in other markdown files. Do I need to remove them?

**Comment by Telemaco019** [comment]
Thanks for fixing the extra character, now the rendering looks ok!

New lines and whitespace should not affect rendering on Mkdocs, but it would be nice to clean them up. If you feel like doing it, that would be great! Otherwise we can already merge the PR 👍

**Comment by WindowsXp-Beta** [comment]
Let me remove them😆.
However, I wonder how these weird lines were generated? Do you use some markdown formatting tools that require the maximum number of characters of a line🤔🤔🤔? If so, maybe I should keep them.

**Pull request merged**
